export const ADD_STOCK_REQUEST = "ADD_STOCK_REQUEST"
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS"
export const ADD_STOCK_FAIL = "ADD_STOCK_FAIL"

export const GET_ALL_STOCK_REQUEST = "GET_ALL_STOCK_REQUEST"
export const GET_ALL_STOCK_SUCCESS = "GET_ALL_STOCK_SUCCESS"
export const GET_ALL_STOCK_FAIL = "GET_ALL_STOCK_FAIL"

export const STOCK_DETAILS_REQUEST = "STOCK_DETAILS_REQUEST"
export const STOCK_DETAILS_SUCCESS = "STOCK_DETAILS_SUCCESS"
export const STOCK_DETAILS_FAIL = "STOCK_DETAILS_FAIL"

export const DELETE_STOCK_REQUEST = "DELETE_STOCK_REQUEST"
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS"
export const DELETE_STOCK_FAIL = "DELETE_STOCK_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"